package com.qmspharma.model.enums;

public enum CapaStatus {
    INITIATED, UNDER_REVIEW, INVESTIGATION, ROOT_CAUSE_IDENTIFIED,
    ACTION_PLANNING, ACTION_IN_PROGRESS, EFFECTIVENESS_CHECK,
    PENDING_CLOSURE, CLOSED, REJECTED
}
