package com.qmspharma.model.enums;

public enum UserType {
    OPERATOR, QA_SPECIALIST, QUALITY_MANAGER, CAPA_COORDINATOR,
    INVESTIGATOR_SME, CHANGE_OWNER, DOC_CONTROL_SPECIALIST,
    TRAINING_ADMIN, AUDITOR, SITE_QUALITY_HEAD,
    SYSTEM_ADMIN, EXTERNAL_SUPPLIER,
    SUPPLIER_QUALITY_MANAGER, COMPLAINT_HANDLER, VALIDATION_ENGINEER,
    MAINTENANCE_USER, EXECUTIVE, REGULATORY_AFFAIRS
}
