package com.qmspharma.model.enums;

public enum AiSuggestionType {
    DEVIATION_CLASSIFICATION,
    DEVIATION_ROOT_CAUSE,
    DEVIATION_IMPACT_ASSESSMENT,
    CAPA_RECOMMENDATION,
    CAPA_ACTION_PLAN,
    CAPA_EFFECTIVENESS_PREDICTION,
    COMPLAINT_TRIAGE,
    COMPLAINT_ADVERSE_EVENT,
    COMPLAINT_RECALL_ASSESSMENT,
    AUDIT_FINDING_CLASSIFICATION,
    AUDIT_CHECKLIST,
    AUDIT_PLAN,
    DOCUMENT_DRAFT,
    DOCUMENT_GXP_VALIDATION,
    TRAINING_GAP_DETECTION,
    TRAINING_LEARNING_PATH,
    SUPPLIER_RISK_SCORE,
    SUPPLIER_QUALIFICATION,
    EQUIPMENT_MAINTENANCE_PREDICTION,
    NC_CLASSIFICATION,
    NC_DISPOSITION,
    RISK_ASSESSMENT,
    CHANGE_IMPACT_ASSESSMENT,
    CROSS_MODULE_WORKFLOW,
    INVESTIGATION_REPORT
}
