package com.qmspharma.model.enums;

public enum ChangeStatus {
    DRAFT, SUBMITTED, IMPACT_ASSESSMENT, QA_REVIEW,
    RA_REVIEW, PENDING_APPROVAL, APPROVED, IMPLEMENTATION,
    VERIFICATION, EFFECTIVENESS_CHECK, CLOSED, REJECTED, WITHDRAWN
}
