-- V16: Add AUDIT_PLAN and AUDIT_FINDING to audit_trail record_type constraint

ALTER TABLE audit_trail DROP CONSTRAINT IF EXISTS audit_trail_record_type_check;
ALTER TABLE audit_trail ADD CONSTRAINT audit_trail_record_type_check
  CHECK (record_type IN (
    'CAPA', 'DEVIATION', 'CHANGE_CONTROL', 'USER', 'ROLE',
    'DOCUMENT', 'TRAINING', 'TRAINING_ASSIGNMENT', 'TRAINING_CURRICULUM',
    'SYSTEM_CONFIG', 'RISK_ASSESSMENT', 'AUDIT', 'AUDIT_PLAN', 'AUDIT_FINDING',
    'SUPPLIER', 'COMPLAINT', 'NONCONFORMANCE', 'EQUIPMENT', 'CALIBRATION',
    'VALIDATION', 'MANAGEMENT_REVIEW', 'REGULATORY_COMMITMENT'
  ));
